--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cosmicnebula200/CommandPermissionMessage
build-by-default: true
branches:
- main
projects:
  CommandPermissionMessage:
    path: ""
...
